### ISSUE TITLE
dependency not found

### ISSUE THREAD

**Issue by CaoYouXin** [linux-china/spring-boot-starter-httpclient#2]

**Comment by EddyChina** [comment]
same issue. @CaoYouXin @linux-china

**Comment by linux-china** [comment]
please run 'maven -DskipTests clean source:jar package install " to install the artifact to local maven repository or deploy to your private maven repository

**Comment by EddyChina** [comment]
@linux-china  still doesn't work.  here is the error message

> could not find artifact org.mvnsearch.spring.boot:spring-boot-starter-httpclient:jar:1.0.0-SNAPSHOT in spring-snapshot (https://repo.spring.io/snapshot) -> [Help 1]

**Comment by EddyChina** [comment]
Also

> [WARNING] The POM for org.mvnsearch.spring.boot:spring-boot-starter-httpclient:jar:1.0.0-SNAPSHOT is missing, no dependency information available
